### ISSUE TITLE
Upstream contribution package: port the transport codec (LEPUS_REF crash fix), pipeline entries, and the ART diagnosis to octanejs/octane

### ISSUE THREAD

**Issue by Huxpro** [Huxpro/octane#232]
# What this is

A self-contained spec for contributing three things from the `new-lynx` campaign back to `octanejs/octane`. It is written to be executed from an environment with upstream PR access and **no other context** — everything needed is named here. Deliverable 1 is the load-bearing one; 2 and 3 ride behind it. Together they unblock upstream's entire native (LepusNG) story and its featured-Native eligibility in lynx-js-framework-benchmark.

## Deliverable 1 — Port the transport codec: the `Reflect.ownKeys` × `LEPUS_REF` device crash

**The defect, as it stands on upstream `main` today.** `ContextProxy` transports generic Lynx values. On device, a composite sent through it can arrive in LepusNG as `LEPUS_TAG_LEPUS_REF`: a host-backed engine value that answers `typeof`, property reads, spread, and `JSON.stringify` — but is not an ordinary receiver-realm object. On it, **`Reflect.ownKeys` throws**, `Object(v) !== v`, and the prototype is `null`. Reproduced on both iOS and Android (evidence archived in Huxpro/octane#152). Upstream's receive-side today mixes two readers: `Object.getOwnPropertyNames` (upstream `packages/lynx/src/main-thread.ts:248`, `core/protocol.ts:599`, `core/worklets.ts:152`) — which performs `ToObject` and *accidentally* coerces the bridge value into something enumerable, an accident that has been load-bearing for the package's whole native lifetime — and the non-coercing `Reflect.ownKeys` (`core/protocol.ts:472`, `:768`, `:797`, `:1206`), which crashes the renderer on device the moment a bridged composite reaches it. The defect was never either call: it is that a bridged value reaches receiver code at all.

**The fix, already built and battle-tested on `new-lynx`.** `packages/lynx/src/core/transport-codec.ts` (landed via Huxpro/octane#164): composites cross the `ContextProxy` as **encoded text**, the receive path decodes before anything reads the payload, and the invariant is one sentence — *a `LynxValueRef` never escapes the transport layer; everything above it sees only `LynxStructuredValue`*. The codec also owns exactly the cases where plain JSON silently changes meaning (`undefined` keys, `NaN`/`±Infinity`, `bigint`, functions/symbols, `__proto__`-class keys — each throws or round-trips by design, never silently). The module is self-contained — it was re-integrated wholesale into a heavily diverged tree during the C8–D8 reconciliation without modification, which is the portability proof.

**Port checklist:**
- Branch from `octanejs/octane@main` (do NOT base on `new-lynx`; carry nothing program-related).
- Bring over: `packages/lynx/src/core/transport-codec.ts`; the encode call at the transport send sites and the decode-first block at the top of `receive()` in `main-thread.ts` (see `new-lynx`'s `main-thread.ts` — the `decodeLynxTransportValue` try/catch before any payload read, including the recovery path) and the mirror on the background side in `core/transport.ts`; the test suites `packages/lynx/tests/transport-codec.test.ts` and `transport-conformance.test.ts` plus the `tests/_fixtures/lynx-wire.ts` fixture. Adapt upstream tests that dispatch raw objects onto the wire to use the `wire()`/`unwire()` fixture (the same adaptation `new-lynx` made; grep `dispatchEvent` in upstream's lynx tests).
- Do NOT bring the validation-mode plumbing (`resolveLynxValidationMode`, checked/trusted) — that is a separate `new-lynx` layer; the codec alone stops the crash. Both realms ship from one bundle, so there is no wire-format version negotiation to design.
- After the port, upstream's remaining direct readers of `event.data` composites (`getOwnPropertyNames` sites above) should be reading decoded `LynxStructuredValue` — audit each and say so in the PR body per site.

**PR narrative for upstream maintainers** (they need the history to trust it): lead with the repro (#152's iOS+Android evidence), then the accident history — `Object.getOwnPropertyNames`'s `ToObject` coercion is why the code *appears* to work, and any migration toward `Reflect.ownKeys` (already present at four receive-path sites) detonates on device. The codec removes the class, not the instance. Include a before/after: a bridged-composite fixture that throws at `protocol.ts:472` before the port and round-trips after.

## Deliverable 2 — Standard Lynx pipeline performance entries (Huxpro/octane#199, executed against upstream)

lynx-js-framework-benchmark reports Native startup from the platform's own pipeline boundary (`openTime → totalFcp` via `Performance.getAllPerformanceEntries`) and its methodology records: *"Octane's custom renderer does not expose the same pipeline boundary in this Explorer build, so no featured Native Octane metric is reported."* Implement #199's spec **against upstream `main`** so the whole project gains featured-Native eligibility: find the platform's real marking contract (whether the engine stamps entries around `__FlushElementTree`-adjacent internals or expects a framework call), map upstream's first-screen boundaries onto it honestly (no invented moments, entries stamped where platform semantics say), and pin one-entry-per-first-screen in a test. Acceptance is the benchmark's Native adapter reading the entries for an Octane bundle in LynxExplorer with `enable_perf_metrics`. This lands as a second, independent PR — do not couple it to the codec port.

## Deliverable 3 — The ART reference-table diagnosis (issue first, fix conditional)

On device, creating ~51,200 elements overflows ART's global reference table (`max=51200`) and aborts natively (Huxpro/octane#194 round 1: 5/5 crash at 10k rows × 7 elements; the counting arithmetic and a separating experiment design are in Huxpro/octane#222). Upstream's first-screen path retains **more** per element than `new-lynx` post-D-train (per-node records + `ownedNodes` + per-node event journal), so it hits the same wall no later and likely earlier. File this as an **upstream issue** carrying: the crash signature, the ~1-entry-per-created-element arithmetic, the threshold math, the `--retain none` experiment design, and the ART-table-dump capture protocol from #222 — so upstream goes from "mysterious native crash at scale" to "known cause with a ready experiment". Attach a fix PR only after Huxpro's device round 2 settles whether retention (fixable) or creation (not fixable from JS) drives the table; do not guess ahead of that data.

## Validation bar (both PRs)

Upstream's own gates on the port branch: full test run, typecheck, lint/format as `octanejs/octane` defines them — plus the ported suites green. No behavior change on the web path is expected from Deliverable 1 (the codec is encode/decode symmetric; upstream's web tests are the guard). Keep each PR minimal and independent; the campaign's program/adoption work stays out entirely.

**Comment by Huxpro** [comment]
D2 audit found a current-state conflict that should be recorded before changing the plan.

The latest #199 device acceptance run already established that LynxExplorer stamped **exactly one standard `loadBundle` pipeline entry** for the clean `new-lynx` bundle (`openTime`, `totalFcp`, `lynxFcp`, and `pipelineEnd` were all present). It also established that this entry was not evidence of a successful Octane first screen: both runtimes failed with `ReferenceError: MessageChannel is not defined`, and the required `lynx-native-startup-v1` two-frame/semantic producer receipt never appeared. The adapter correctly retained the cell as DNF.

That changes the premise of D2 in this package:

1. The platform entry is already engine-stamped; no Octane timing-mark call has been identified or justified.
2. The entry can exist when the application never completes a verifiable first screen, so adding an Octane-side marker would risk a duplicate entry or a second false-positive boundary.
3. The observed `MessageChannel` crash is specific to the tested `new-lynx` snapshot. Current `octanejs/octane@main` already guards `MessageChannel` in `packages/octane/src/runtime.ts` and falls back to `setTimeout`, so that failure should not be projected onto upstream without a fresh bundle/device acceptance run.
4. The benchmark's current checked-in adapter intentionally suppresses `Performance.getAllPerformanceEntries` for the current Octane entry and falls back to the private receipt path, while its standard path requires both the engine entry and the versioned producer receipt. Thus upstream acceptance needs a fixture/adapter mode that preserves the real black-box query and emits the semantic receipt; a renderer timing patch by itself cannot satisfy the consumer.

I will therefore not silently add a speculative `__FlushElementTree`-adjacent timing hook. I am continuing D2 as a minimal, independent upstream audit/acceptance change: identify the existing producer fixture and direct vs decline→fallback/adoption paths, add only the missing conformance/receipt coverage supported by the actual platform contract, then run the same LynxExplorer adapter acceptance. If that audit finds no honest upstream code change beyond verification, I will report that rather than manufacture a second timing implementation.

This does not affect D1: the codec PR remains independent and already contains no timing/program/adoption changes.

**Comment by Huxpro** [comment]
D2 exact-device acceptance produced a second current-state conflict, so I am recording it before changing any implementation or acceptance plan.

Using the exact bundle from the independent upstream branch/PR ([octanejs/octane#886](https://github.com/octanejs/octane/pull/886), SHA-256 `5f7646aca90fab3a6be72ec756018676f59b13bcf1d7649bb6d782f167b1a015`) on leased Lynx Sandbox device `aic-i18n-bd-fullport.byteintl.net:55864`, LynxExplorer did fetch the pinned bytes and created session 2, but the standard startup probe timed out after 240 s with:

```json
{
  "performanceEntryCount": 0,
  "pipelineEntries": [],
  "timingInfo": {
    "extraTiming": {
      "container_init_start": 1787921782247,
      "container_init_end": 1787921782251,
      "prepare_template_start": 1787921782253,
      "prepare_template_end": 1787921782253,
      "open_time": 1787921782247
    }
  }
}
```

The required `lynx-native-startup-v1` producer receipt was also absent. Error-level Android logs show no application exception; the only errors at teardown are the expected DebugRouter socket closure. This differs from #199, where a failed bundle still yielded exactly one `loadBundle` pipeline entry with both `lynxFcp` and `totalFcp`.

I am keeping #886 in Draft and will not add a speculative Octane-side pipeline marker. Next I am isolating whether this is a fixture/build compatibility problem or a LynxExplorer perf-instrumentation difference on the leased image. Any resulting plan change will be posted here before altering D2.

**Comment by Huxpro** [comment]
The follow-up controls isolate both failures and expose one more D1/D2 integration constraint before I change the acceptance procedure:

* On the same leased device, the repository's known-good `vue-vdom` rows-0 bundle emitted a valid `lynx-native-startup-v1` receipt (`moduleStartMs=1787922125891`, first frame `1787922125897`, second frame `1787922125913`, correct rows-0 semantic state), while `Performance.getAllPerformanceEntries` still returned `[]`. This confirms the current LynxExplorer image lacks the standard perf entry for every framework, not just Octane.
* The D2 bundle itself executes far enough to install `__LYNX_BENCH_SNAPSHOT__` as a function and return the correct rows-0 state, with no producer error, but `root.render()` never resolves its transport acknowledgement. Therefore no honest `commitAckMs` or two-frame receipt can be published.

That second observation matches D1's load-bearing defect: D2 is intentionally based on unmodified upstream `main`, whose first background-to-main composite can die at the `LEPUS_REF`/`Reflect.ownKeys` receive path before the ACK returns. It also explains why a historical codec-bearing benchmark bundle could report commit acknowledgements while this independent D2 branch cannot.

I will keep the PRs independent (no codec commit or source copied into #886), but change **only the device acceptance build** to a local integration overlay of the already-published D1 commit plus D2. The acceptance record will identify both commits and will not claim that D2 alone fixes the transport crash. Platform-pipeline acceptance remains unavailable on this device image; a successful producer receipt will prove D2's fixture boundary, not manufacture or substitute the engine entry.

**Comment by Huxpro** [comment]
Correction to my preceding inference: the local D1+D2 integration overlay does **not** restore the D2 producer acknowledgement.

I built D2 commit `7378d00477a09ed33db28f5578e5c6b674b83f9e` with D1 commit `2b2465719eef` applied only in a disposable acceptance checkout. The resulting 492,867-byte bundle (`sha256:6cebf2d0bf496f049657a2ca3585385d8f59cb85d8b0efa226ddec5b79a09634`) still timed out after 30 s with no startup receipt. Therefore the earlier “D1's LEPUS_REF crash explains the missing ACK” statement was a plausible but falsified hypothesis; it must not be used as the PR rationale.

I am reverting the acceptance plan to audit mode, with #886 remaining Draft. Next controls are the #199 Explorer/package version and a historical Octane bundle known to have produced transport acknowledgements. I will not add codec coupling, program/adoption changes, or an Octane-side timing marker based on this failed overlay.

**Comment by Huxpro** [comment]
Final device controls establish that D2 is blocked by two external/current-main conditions rather than an undiscovered Octane pipeline-mark call:

1. The archived Octane `0fc84da0` rows-0 bundle, which previously produced Native ACK evidence, still does so on this exact device: `moduleStartMs=1787922635481`, `commitAckMs=1787922635521`, first frame `1787922635523`, second frame `1787922635540`. The current device can therefore execute Octane background transport and two-frame instrumentation.
2. That historical Octane bundle and the known-good current `vue-vdom` bundle both receive zero `Performance.getAllPerformanceEntries` entries on this Explorer install (`com.lynx.explorer` versionName `1.0`, versionCode `1`, installed 2026-08-20). In contrast, #199's earlier device image emitted one engine-owned `loadBundle` entry even for a crashing app. The standard entry is image/engine supplied, not something current upstream Octane can honestly synthesize.
3. Current upstream D2, both alone and with D1 overlaid, renders enough background state to install the semantic snapshot but never receives the `root.render()` commit acknowledgement. The historical control proves this is a current-main transport/first-screen regression, but the D1 overlay falsifies the specific codec-crash hypothesis. Fixing it would require a separate renderer investigation and may enter the program/adoption area explicitly out of scope for this contribution package.

Accordingly #886 remains Draft and records the useful independent fixture changes and complete upstream gates, but its device acceptance is honestly failed. I will not call the private receipt a platform entry, add a duplicate marker, or import `new-lynx` program/adoption work to force the result.

**Comment by Huxpro** [comment]
D3's prerequisite has now changed: #194 device round 2 is complete, so the “fix conditional after retention vs creation settles” clause can be resolved before opening the upstream issue.

The exact 10k D-train program cell crashed 5/5 at 20,397–22,029 ms (median 21,156 ms). Every ART dump was dominated by:

- 30,026 `com.lynx.tasm.behavior.PaintingContext$a`
- 20,444 `m7.w`

Only hundreds of `java.lang.Class` / `DirectByteBuffer` entries followed. This names Lynx platform UI holders, not an Octane JavaScript container. Following #222's predeclared stop condition, the runner skipped the 6k–8k bisection and all program/direct/retain-none arms: creation itself had already identified the capacity owner, so a JS retention release-point experiment could not change the decision.

I will therefore execute D3 as **issue only, no conditional fix PR**. The upstream issue will preserve the original crash signature, element-count and threshold arithmetic, retain-none design, and ART-dump capture protocol, while clearly recording that round 2 superseded the unrun experiment: this is a platform creation/capacity boundary, not evidence for deleting an Octane retention map. I will not silently carry #232's older “round 2 pending” wording forward.

**Comment by Huxpro** [comment]
D2 correction: the archived 0fc84da0 control does not by itself prove a current-main renderer regression, because it and #886 carry materially different fixture patches.

I rebuilt the historical bases after fixing a dependency-isolation bug in my disposable checkouts. The reused package node_modules directory contained a relative @octanejs/lynx symlink, so the first historical builds still resolved to the current checkout. After copying the package-local node_modules layouts, each candidate resolved @octanejs/lynx and octane to its own checkout.

On the same leased device (aic-i18n-bd-fullport.byteintl.net:51306):

- The immutable archived 0fc84da0 rows-0 bundle (491,598 bytes, sha256 1f3b252db1392d42f7173e77f4d49302497038bd8ca2e29c5ca077028a4b7497) again returned moduleStartMs=1787923760389, commitAckMs=1787923760430, and frames at 1787923760432 / 1787923760448.
- A correctly isolated 0fc84da0 checkout with the exact #886 patch produced a 486,516-byte bundle (sha256 a7a8a1875df9e4a6e6b66c85b9a0d848c04c5a06ff172199e4fe4c514f1b339e) but returned a thenable from root.render() and never settled its transport acknowledgement within 30 seconds.
- A temporary phase probe showed render-returned:object:true continuously, with no ACK/rejection.
- Restoring the original App while keeping the D2 index probe stopped before the index module body because Native lacks MessageChannel. This confirms the MessageChannel fallback is necessary.
- Keeping that fallback while removing the entire semantic snapshot hook/global block still returned the thenable and never ACKed. The snapshot addition is therefore not the cause.

The archived bundle includes the benchmark repository's much larger historical Native instrumentation patch (operation measurement, flush hooks, driver surface, and different event-handler shapes); #886 intentionally carries only the minimum fallback/snapshot/startup-receipt slice. The archived success therefore proves the device and an Octane fixture can ACK, but it does not yet locate the difference in an upstream commit range.

I am withdrawing the earlier claim that the control alone establishes a current-main transport/first-screen regression. #886 remains Draft. Next I am auditing the remaining fixture-shape difference and whether the successful archived fixture selected a different direct-vs-decline first-screen path. I will not import or modify program/adoption code, and I will post any resulting scope conflict here before changing the PR.

**Comment by Huxpro** [comment]
D2 follow-up: the final orthogonal control isolates a second transport prerequisite, but it still does not produce the standard platform pipeline entry.

On the same leased device (aic-i18n-bd-fullport.byteintl.net:51306):

1. D2 plus only a 16 ms correlated main-ready-request retry produced a 493,138-byte bundle (sha256 1a337ac9848ab0a108eeafc14c0d3fbebdee90ea06aaa1911f85b7edb8905795). It still timed out after 30 seconds with no ACK or startup receipt.
2. D1 plus D2 plus the identical readiness retry produced a 499,299-byte bundle (sha256 3decf55d953631cd2d656f7ba7615941a28a793a6b65931da42e91f2497429e6). It immediately emitted a fully valid lynx-native-startup-v1 receipt:
   - openTime: 1787924596246
   - moduleStartMs: 1787924596401
   - commitAckMs: 1787924596456
   - firstFrameMs: 1787924596463
   - secondFrameMs: 1787924596480
   - rows-0 semantic postState: all expected null IDs/label, rowCount 0

This explains why the immutable archived 0fc84da0 bundle succeeds: its preserved patch contains both a production string wire and a repeating readiness request. Current upstream has only a one-shot initial request plus one announcement-triggered resend. If main and background each emit before the peer listener exists, both one-shot messages are lost and the roots wait forever. The repeating correlated request closes that listener-installation race; duplicate IDs are already idempotent on main.

The controls establish two independent prerequisites for a truthful D2 producer receipt:

- D1's encoded string wire, and
- a separate readiness-handshake retry.

They do not establish the requested D2 platform contract: Performance.getAllPerformanceEntries remained empty, and the successful observation is still the private producer fallback. I therefore will not silently add the readiness fix to #886, claim that the private receipt is a platform entry, or call D2 accepted. Adding it now would introduce a second transport bug fix into a pipeline-entry PR and make its device success contingent on a local D1 overlay, contrary to the independent-minimal-PR constraint.

#886 remains Draft while I preserve this evidence. Any decision to move the readiness race into a separately reviewed transport fix, fold it into D1, or defer D2 until both transport prerequisites land needs an explicit scope decision; it cannot be inferred from #199's pipeline-entry deliverable.

**Comment by Huxpro** [comment]
Readiness follow-up after D1 landed upstream:

The current `main` transport now sends its correlated readiness request after installing the background listener and performs one additional send when it sees main's unsolicited request-0 announcement. On Native, however, those two sends can still both occur before main installs its peer listener. That conflicts with the earlier assumption that D1's listener ordering plus the one-shot announcement retry closed the startup race.

Per the newly authorized option 1, I am keeping the correction independent: a minimal readiness-transport PR will repeat the **same correlated request id** every 16 ms until the correlated reply arrives or the transport closes. It changes no wire keys, capability rungs, first-tree behavior, `getOwnPropertyNames` sites, D2 performance-entry code, or program/adoption scope. The liveness semantics follow the already device-verified readiness/presence family in #233, but the implementation is rewritten around upstream's current transport lifecycle and tombstone handling. D2 remains unchanged and its device acceptance stack will be `main` (including #885) + readiness PR + #886.

Validation/status notes that should not be hidden:

- The focused readiness regression is red before the transport change and green after it; the complete Lynx Vitest project is green (27 files, 395 tests), including the ported transport/codec suite.
- Upstream's official root `pnpm typecheck`, `pnpm format:check`, `pnpm sync`, and `pnpm changeset:check` are green. The package-local `pnpm --filter @octanejs/lynx typecheck` invokes `tsc` instead of the root gate's `tsgo` and is base-red on unchanged `main-thread.ts` (`adoption` is inferred as `string`); no unrelated fix is being folded into this PR.
- A monolithic local `pnpm test` attempt exhausted the host's shared `/tmp` and file-descriptor limits (`ENOSPC`/`EMFILE`), cascading into 1,314 suites that never collected. This is environmental rather than a readiness assertion failure. I will rely on the repository's official four-way CI shard plus its dedicated heavy/browser/parity jobs on the PR for the complete upstream gate, rather than change scope or silently describe that local run as green.

If upstream CI exposes a semantic conflict rather than an environmental failure, I will report it here before changing the plan.

**Comment by Huxpro** [comment]
Device-stack correction before changing #909:

The first `main + #909 + #886` Native run did not reach D2's startup receipt. LynxExplorer loaded the bundle, but background startup failed with:

```text
TypeError: globalThis.setTimeout is not a function
```

The device runtime exposes the host timer binding used by the already verified fork implementation, but does not expose it as a `globalThis` property. This conflicts with my initial upstream rewrite, which qualified the timer as `globalThis.setTimeout` / `globalThis.clearTimeout`. I converted octanejs/octane#909 back to Draft before changing it.

Planned correction is intentionally narrow: use the bare host bindings `setTimeout` and `clearTimeout`, exactly at the two readiness lifecycle call sites. The same-id 16 ms readiness semantics, stop conditions, tests, protocol shape, D2 patch, and PR scope remain unchanged. I will rebuild and rerun the exact device stack after the correction, and report the resulting receipt/error evidence here and on #886.

**Comment by Huxpro** [comment]
Device-stack result after the narrow timer-binding correction in octanejs/octane#909:

- Official Lynx documents `setTimeout` as a bare background-thread global. #909 now matches that API and the already verified fork implementation; focused protocol tests and source typecheck remain green.
- The currently leased Sandbox LynxExplorer reports SDK `0.0.1` and evaluates both `globalThis.setTimeout` and bare `setTimeout` as unavailable. It therefore cannot exercise the 16 ms late-listener path or serve as D2's startup-receipt acceptance environment.
- On the exact disposable stack `upstream main (including #885) + #909@9994674bba + #886@7378d00477`, the corrected production bundle loads and exposes the expected 1000-row semantic snapshot:

```json
{"rowCount":1000,"firstId":1,"secondId":2,"thirdId":3,"row998Id":999,"firstLabel":"pretty red table","selectedId":null}
```

  The startup receipt remains `null` on this image, so ACK/two-frame acceptance is **not** claimed. There is no application error after the correction.

This matches the previously stated environment constraint: the readiness semantics remain supported by the compatible-device evidence behind Huxpro/octane#233, while this Explorer image is missing the timer primitive required to reproduce them. I am not changing #886 or broadening #909 to polyfill an old host runtime. #909 stays a readiness-only PR and will use upstream's complete CI gate; #886 remains Draft with its exact-device acceptance gap explicit.

**Comment by Huxpro** [comment]
Final readiness-PR gate result:

- [octanejs/octane#909](https://github.com/octanejs/octane/pull/909) is Ready at `9994674bba` and remains limited to the readiness transport, two protocol regressions, and one package changeset.
- [official CI run 33311512894](https://github.com/octanejs/octane/actions/runs/33311512894) completed successfully: 4/4 Node 24 test shards, 4/4 React parity shards plus aggregate, heavy package/Astro, heavy Chromium, website, 3/3 example shards plus aggregate, publishable-package validation, Three/Lynx compatibility, lint, typecheck, and provenance all passed.
- Local post-correction evidence is also green: Lynx 27 files / 395 tests, focused protocol 47/47, all three Lynx tsgo configs, source-file typecheck, full format check, sync, and changeset check.
- The current Sandbox image limitation and the exact `main + #909 + #886` semantic snapshot are recorded above; ACK/two-frame device acceptance is still not claimed on an Explorer SDK that lacks the documented timer global. No workaround or scope expansion was added.

D1 #885 remains merged, D3 #888 remains issue-only, and D2 #886 remains code-identical/Draft pending a compatible device environment.

**Comment by Huxpro** [comment]
Final state-audit correction (no silent PR-state change):

The GitHub API reports #886 as Ready, not Draft. Its timeline shows maintainer `trueadm` changed it to Ready at `2026-08-30T11:26:56Z`, after my earlier Draft conversion and before this final audit. The head SHA and three-file patch are unchanged at `7378d00477`.

My immediately preceding comments incorrectly repeated the stale “remains Draft” state. I am **not** overriding the maintainer's Ready action. The evidence statement is unchanged: the available Explorer image cannot claim ACK/two-frame acceptance, and that limitation is recorded on #886; #909 remains an independent Ready PR with green CI. Any decision to convert #886 back to Draft now belongs to upstream review rather than an unannounced plan mutation.
